package Vista.Paneles.Reportes;

import static Controlador.Pruebas.setColumnsTable;
import DML.DML;
import Modelo.ConexionBD;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EduardoCGarcia
 */
public class Reporte1 extends javax.swing.JPanel {

    private String usuario;
    private String password;

    /**
     * Creates new form ReportesLibros
     */
    public Reporte1() {
        initComponents();
        this.crearTabla();
    }

    public Reporte1(String usuario, String password) {
        initComponents();
        
        this.usuario = usuario;
        this.password = password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listado de libros con los que cuenta cada sucursal de biblioteca");

        tblContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblContent);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre de los libros que hayan sido solicitados para préstamos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContent;
    // End of variables declaration//GEN-END:variables

    public void crearTabla(){
        DefaultTableModel modelo =  setColumnsTable();
        try {
            ConexionBD conexion = new ConexionBD();
            conexion.estableceConexion("root", "");
            PreparedStatement pst;
            pst = conexion.cn.prepareStatement("SELECT libro.Nombre AS nombre_libro, lector.Nombre \n"
                    + "AS nombre_lector, prestamos.Fecha_Sale FROM libro,lector,prestamos \n"
                    + "where libro.ID_Libro = prestamos.ID_Libro \n"
                    + "AND lector.Num_Targeta = prestamos.Num_Targeta\n"
                    + "ORDER BY prestamos.Fecha_Sale");

            ResultSet rs = pst.executeQuery();
            int i = 0;
            while (rs.next()) {
                System.out.println(rs.getString("nombre_libro"));
                String filas[] = {
                    String.format(rs.getString("nombre_libro")),
                    String.format(rs.getString("nombre_lector")),
                    String.format(rs.getString("Fecha_Sale"))
                };
                modelo.addRow(filas);
            }
            
            this.tblContent.setModel(modelo);
            

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public static DefaultTableModel setColumnsTable(){
        DefaultTableModel modelo =  new DefaultTableModel();
        /*Establecemos las columnas*/
        ArrayList<String> columnas = new ArrayList<String> ();
        columnas.add("nombre_libro");
        columnas.add("nombre_lector");
        columnas.add("Fecha_Sale");
        
        for(Object col:columnas){
            modelo.addColumn(col);
        }
        return modelo;
    }

}
