package Vista.Paneles;

import Utilerias.GUITools;
import Vista.Paneles.Eliminar.DeleteClientePanel;
import Vista.Paneles.Eliminar.DeleteLibroPanel;
import Vista.Paneles.Eliminar.DeleteSucursalPanel;
import Vista.Paneles.Registrar.CreateClientePanel;
import Vista.Paneles.Registrar.CreateLibrosPanel;
import Vista.Paneles.Registrar.CreateSucursalPanel;
import Vista.Paneles.Reportes.*;
import Vista.app;

/**
 *
 * @author Gonzalo CH
 */
public class PanelCD extends javax.swing.JPanel {

    private String usuario;
    private String password;

    /**
     * Creates new form Libros
     */
    public PanelCD(String usuario, String password) {
        initComponents();
        lblTitle.setText(app.typePanelCD);
        cbxNombreReporte.setVisible(false);
        this.usuario = usuario;
        this.password = password;
    }

    public PanelCD() {
        initComponents();
        lblTitle.setText(app.typePanelCD);
        cbxNombreReporte.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new Utilerias.FondoImagen("TexturaBlanco1.jpeg");
        lblTitle = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        Libro = new Utilerias.FondoImagen("LibroAbierto1.jpg");
        cbxNombreReporte = new javax.swing.JComboBox<>();

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Libros");

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar", "Eliminar", "Reportes" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel1.setText("¿Que accion deseas realizar?");

        btnContinuar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LibroLayout = new javax.swing.GroupLayout(Libro);
        Libro.setLayout(LibroLayout);
        LibroLayout.setHorizontalGroup(
            LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        LibroLayout.setVerticalGroup(
            LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        cbxNombreReporte.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cbxNombreReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre de los libros que hayan sido solicitados para préstamos.", "Listado de libros con los que cuenta cada sucursal de biblioteca.", "Listado de libros que están en préstamo de acuerdo a una fecha de salida.", "Listado de los lectores que han solicitado libros en una fecha de devolucion." }));
        cbxNombreReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNombreReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addComponent(Libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addComponent(btnContinuar)
                        .addGap(252, 252, 252))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(205, 205, 205))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxNombreReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(cbxNombreReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnContinuar)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        if (app.typePanelCD.equals("LIBRO")) {
            if (String.valueOf(jComboBox1.getSelectedItem()).equals("Eliminar")) {
                DeleteLibroPanel p = new DeleteLibroPanel();
                //DeleteLibroPanel p = new DeleteLibroPanel(this.usuario,this.password);
                GUITools.panelIntoPanel(this, p);
            } else if (String.valueOf(jComboBox1.getSelectedItem()).equals("Registrar")) {
                CreateLibrosPanel p = new CreateLibrosPanel();
                //CreateLibrosPanel p = new CreateLibrosPanel(this.usuario,this.password);
                GUITools.panelIntoPanel(this, p);
            } else {
                if (cbxNombreReporte.getSelectedIndex() == 0) {
                    Reporte1 lib = new Reporte1();
                    //Reporte1 lib = new Reporte1(this.usuario, this.password);
                    GUITools.panelIntoPanel(this, lib);
                } else if (cbxNombreReporte.getSelectedIndex() == 1) {
                    Reportes2 lib = new Reportes2();
                    //Reportes2 lib = new Reportes2(this.usuario,this.password);
                    GUITools.panelIntoPanel(this, lib);
                } else if (cbxNombreReporte.getSelectedIndex() == 2) {
                    Reporte3 lib = new Reporte3();
                    //Reporte3 lib = new Reporte3(this.usuario, this.password);
                    GUITools.panelIntoPanel(this, lib);
                } else {
                    //Reporte4 lib = new Reporte4();
                    Reporte4 lib = new Reporte4();
                    GUITools.panelIntoPanel(this, lib);
                }
            }
        }

        if (app.typePanelCD.equals("CLIENTE")) {
            if (String.valueOf(jComboBox1.getSelectedItem()).equals("Registrar")) {
                CreateClientePanel p = new CreateClientePanel();
                //CreateClientePanel p = new CreateClientePanel(this.usuario,this.password);
                GUITools.panelIntoPanel(this, p);
            } else {
                DeleteClientePanel p = new DeleteClientePanel();
                //DeleteClientePanel p = new DeleteClientePanel(this.usuario,this.password);
                GUITools.panelIntoPanel(this, p);
            }
        }

        if (app.typePanelCD.equals("SUCURSALES")) {
            if (String.valueOf(jComboBox1.getSelectedItem()).equals("Registrar")) {
                CreateSucursalPanel p = new CreateSucursalPanel();
                //CreateSucursalPanel p = new CreateSucursalPanel(this.usuario,this.password);
                GUITools.panelIntoPanel(this, p);
            } else {
                //DeleteSucursalPanel p = new DeleteSucursalPanel();
                DeleteSucursalPanel p = new DeleteSucursalPanel(this.usuario,this.password);
                GUITools.panelIntoPanel(this, p);
            }
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (jComboBox1.getSelectedIndex() != 2) {
            cbxNombreReporte.setVisible(false);
        } else {
            cbxNombreReporte.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void cbxNombreReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNombreReporteActionPerformed

    }//GEN-LAST:event_cbxNombreReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Libro;
    public javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> cbxNombreReporte;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
